apiVersion: v1
kind: Service
metadata:
  name: dummyrails
spec:
  type: LoadBalancer
  selector:
    app: dummyrails
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
